export const projectsData = [
  {
    id: 1,
    title: 'E-commerce Platform',
    description: 'Full-stack e-commerce platform with payment integration',
    longDescription: 'A complete e-commerce solution with product management, shopping cart, secure payment processing, and order tracking.',
    technologies: ['React', 'Node.js', 'MongoDB', 'Stripe', 'Tailwind CSS'],
    image: '🛍️',
    liveUrl: 'https://example.com',
    githubUrl: 'https://github.com',
    featured: true,
    category: 'web-development',
  },
  {
    id: 2,
    title: 'Task Management App',
    description: 'Collaborative task management tool with real-time updates',
    longDescription: 'A real-time collaborative task management application with user authentication, team collaboration features, and progress tracking.',
    technologies: ['React', 'Firebase', 'Tailwind CSS', 'Redux'],
    image: '✅',
    liveUrl: 'https://example.com',
    githubUrl: 'https://github.com',
    featured: true,
    category: 'web-development',
  },
  {
    id: 3,
    title: 'Blog Platform',
    description: 'Content management system for bloggers',
    longDescription: 'A feature-rich blog platform with markdown support, tagging system, search functionality, and beautiful UI.',
    technologies: ['Next.js', 'PostgreSQL', 'Prisma', 'Tailwind CSS'],
    image: '📝',
    liveUrl: 'https://example.com',
    githubUrl: 'https://github.com',
    featured: true,
    category: 'web-development',
  },
]

export const articlesData = [
  {
    id: 1,
    title: 'Getting Started with React Hooks',
    excerpt: 'Learn how to use React Hooks to manage state and side effects in your functional components.',
    date: 'Jan 15, 2024',
    readTime: '5 min read',
    category: 'React',
    url: '#',
  },
  {
    id: 2,
    title: 'Web Performance Optimization Tips',
    excerpt: 'Discover practical techniques to improve your website\'s performance and user experience.',
    date: 'Jan 10, 2024',
    readTime: '8 min read',
    category: 'Performance',
    url: '#',
  },
  {
    id: 3,
    title: 'Building Beautiful UIs with Framer Motion',
    excerpt: 'A comprehensive guide to creating smooth animations and interactive UIs with Framer Motion.',
    date: 'Jan 5, 2024',
    readTime: '6 min read',
    category: 'Animation',
    url: '#',
  },
]
