export const projectsData = [
  {
    id: 1,
    title: 'CloudOps & Microservices Hub',
    description: 'High-throughput microservices architecture with Redis caching, Docker orchestration, and JWT auth.',
    tagline: 'Full Stack & Distributed Systems',
    technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'Docker', 'Redis'],
    icon: '⚡',
    liveUrl: 'https://github.com/santhoshkumar-01-IT',
    githubUrl: 'https://github.com/santhoshkumar-01-IT',
    featured: true,
    branch: 'main',
    stars: '18',
  },
  {
    id: 2,
    title: 'Collaborative Dev Workflow Engine',
    description: 'Real-time kanban workspace featuring WebSocket state synchronization, granular role-based access, and webhooks.',
    tagline: 'Realtime Web Application',
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Socket.io', 'PostgreSQL'],
    icon: '🚀',
    liveUrl: 'https://github.com/santhoshkumar-01-IT',
    githubUrl: 'https://github.com/santhoshkumar-01-IT',
    featured: true,
    branch: 'release/v2',
    stars: '24',
  },
  {
    id: 3,
    title: 'AI Query & Analytics Dashboard',
    description: 'Interactive data visualization and telemetry platform providing real-time system metrics and AI-driven insights.',
    tagline: 'Data Engineering & Frontend',
    technologies: ['Next.js', 'Python', 'FastAPI', 'Chart.js', 'Tailwind CSS'],
    icon: '🧠',
    liveUrl: 'https://github.com/santhoshkumar-01-IT',
    githubUrl: 'https://github.com/santhoshkumar-01-IT',
    featured: true,
    branch: 'prod',
    stars: '31',
  },
]

export const articlesData = [
  {
    id: 1,
    title: 'Architecting Scalable Microservices with Node.js & Docker',
    excerpt: 'Key strategies for decoupling monolithic architectures into fault-tolerant distributed services with containerized workflows.',
    date: 'Sep 2024',
    readTime: '6 min read',
    category: 'Architecture',
    url: '#',
  },
  {
    id: 2,
    title: 'Optimizing React 19 Client-Side Render Performance',
    excerpt: 'Deep dive into memory footprint profiling, component memoization strategies, and bundle size reduction.',
    date: 'Aug 2024',
    readTime: '5 min read',
    category: 'Frontend Engineering',
    url: '#',
  },
  {
    id: 3,
    title: 'Modern Database Indexing & Query Tuning Patterns',
    excerpt: 'Practical guide to analyzing query plans, composite indexes, and preventing performance bottlenecks in SQL & MongoDB.',
    date: 'Jul 2024',
    readTime: '7 min read',
    category: 'Database Systems',
    url: '#',
  },
]
